export default function () {
    const productData = [
        {
            id: "1",
            name: "Test Shop",
            price: 1000002,
            imageUrl: "https://picsum.photos/600/200",
            isFavorite: false,
        },
        {
            id: "2",
            name: "Test 2",
            price: 20,
            imageUrl: "https://picsum.photos/700/200",
            isFavorite: false,
        },
        {
            id: "3",
            name: "Test 3",
            price: 30,
            imageUrl: "https://picsum.photos/400/200",
            isFavorite: true,
        },
        {
            id: "1",
            name: "Test",
            price: 10,
            imageUrl: "https://picsum.photos/300/200",
            isFavorite: false,
        },
        {
            id: "2",
            name: "Test 2",
            price: 20,
            imageUrl: "https://picsum.photos/900/200",
            isFavorite: false,
        },
        {
            id: "3",
            name: "Test 3",
            price: 30,
            imageUrl: "https://picsum.photos/300/200",
            isFavorite: true,
        },
        {
            id: "1",
            name: "Test",
            price: 10,
            imageUrl: "https://picsum.photos/300/200",
            isFavorite: false,
        },
        {
            id: "2",
            name: "Test 2",
            price: 20,
            imageUrl: "https://picsum.photos/300/200",
            isFavorite: false,
        },
        {
            id: "3",
            name: "Test 3",
            price: 30,
            imageUrl: "https://picsum.photos/300/200",
            isFavorite: true,
        },
        {
            id: "1",
            name: "Test",
            price: 10,
            imageUrl: "https://picsum.photos/300/200",
            isFavorite: false,
        },
        {
            id: "2",
            name: "Test 2",
            price: 20,
            imageUrl: "https://picsum.photos/300/200",
            isFavorite: false,
        },
        {
            id: "3",
            name: "Test 3",
            price: 30,
            imageUrl: "https://picsum.photos/300/200",
            isFavorite: true,
        },
        {
            id: "1",
            name: "Test",
            price: 10,
            imageUrl: "https://picsum.photos/300/200",
            isFavorite: false,
        },
        {
            id: "2",
            name: "Test 2",
            price: 20,
            imageUrl: "https://picsum.photos/300/200",
            isFavorite: false,
        },
        {
            id: "3",
            name: "Test 3",
            price: 30,
            imageUrl: "https://picsum.photos/300/200",
            isFavorite: true,
        },
    ]

    return productData
}
